### ISSUE TITLE
Change code to fix bug

### ISSUE THREAD

**Issue by jaabberwocky** [jaabberwocky/git-training-de#7]
Problem: `main.py` contains a bug which needs fixing. User alerted it to us at 1359hrs on 11 Aug.

**Comment by jaabberwocky** [comment]
Have deployed fix on server. Fix included:

1. Insertion of code logic
2. Deployment on server

**Comment by jaabberwocky** [comment]
If ok, can close this

**Comment by ghost** [comment]
i am the someone else

**Comment by ghost** [comment]
have deployed fix

**Comment by jaabberwocky** [comment]
Provide details of fix pls

**Comment by ghost** [comment]
updated the setting in AWS consoele

**Comment by jaabberwocky** [comment]
Ok im satisfied.

Approved and closed.
